#!/bin/bash

# bootstraps Arch Linux ARM img

set -euo pipefail
IFS=$'\n\t'

pacman -Syu \
  base-devel \
  sudo \
  wpa_supplicant \
  openssh \
  vim \
  htop \
  git \
  cronie \
  python \
  python-pillow \
  ttf-bitstream-vera \
  freetype2

echo '%wheel ALL=(ALL) ALL' >> /etc/sudoers.d/wheel
usermod -a -G wheel alarm

cat <<EOF > wpa_supplicant.conf
ctrl_interface=/run/wpa_supplicant
ctrl_interface_group=wheel
update_config=1

# AP scanning
ap_scan=1

# ISO/IEC alpha2 country code in which the device is operating
country=US

# network section generated by wpa_passphrase
network={
    ssid="${SSID}"
    psk="${PASS}"
}
EOF

ln -s /usr/share/dhcpcd/hooks/10-wpa_supplicant /usr/lib/dhcpcd/dhcpcd-hooks/

echo "device_tree_param=spi=on" >> /boot/config.txt

cat <<EOF > /usr/lib/udev/rules.d/99-spi-permissions.rules
KERNEL=="spidev*", GROUP="tty", MODE="0660"
SUBSYSTEM=="gpio*", PROGRAM="/bin/sh -c 'chown -R root:tty /sys/class/gpio && chmod -R 775 /sys/class/gpio; chown -R
root:tty /sys/devices/virtual/gpio && chmod -R 775 /sys/devices/virtual/gpio; chown -R root:tty
/sys/devices/platform/soc/*.gpio/gpio && chmod -R 775 /sys/devices/platform/soc/*.gpio/gpio'"
SUBSYSTEM=="gpio", KERNEL=="gpiochip*", ACTION=="add", PROGRAM="/bin/sh -c 'chown root:tty /sys/class/gpio/export
/sys/class/gpio/unexport ; chmod 220 /sys/class/gpio/export /sys/class/gpio/unexport'"
SUBSYSTEM=="gpio", KERNEL=="gpio*", ACTION=="add", PROGRAM="/bin/sh -c 'chown root:tty /sys%p/active_low
/sys%p/direction /sys%p/edge /sys%p/value ; chmod 660 /sys%p/active_low /sys%p/direction /sys%p/edge /sys%p/value'"
EOF
usermod -a -G tty alarm

systemctl enable dhcpcd@wlan0
systemctl enable sshd
systemctl enable cronie

su alarm
ssh-keygen -b 2048
cat ~/.ssh/id_rsa.pub
